[package]
name = "age_check_requirement"
type = "contract"
authors = [ "Galactica Network" ]
compiler_version = ">=1.0.0"

[dependencies]
aztec = { git = "https://github.com/aztec-labs-eng/aztec-nr", tag = "v6.0.0-rc.1", directory = "aztec" }
